function toast(message){

  const toast = document.getElementById("toast");

  if(!toast) return;

  toast.textContent = message;

  toast.classList.add("show");

  setTimeout(()=>{
    toast.classList.remove("show");
  },3000);

}

function logout(){

  localStorage.removeItem("fm_session");

  window.location.href = "login.html";

}

const mobileMenu =
  document.getElementById("mobileMenu");

const navLinks =
  document.getElementById("navLinks");

if(mobileMenu){

  mobileMenu.addEventListener("click",()=>{

    navLinks.classList.toggle("active");

  });

}
const LS={users:'fm_users_v3',admins:'fm_admins_v3',products:'fm_products_v3',quotes:'fm_quotes_v3',session:'fm_session_v3',activeQuote:'fm_active_quote_v3'};
const money=n=>Number(n||0).toLocaleString('es-MX',{style:'currency',currency:'MXN'});
const qs=s=>document.querySelector(s); const qsa=s=>[...document.querySelectorAll(s)];
const get=(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)); const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const uid=p=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,8);
function toast(msg,type=''){let t=qs('#toast')||document.body.appendChild(Object.assign(document.createElement('div'),{id:'toast',className:'toast'}));t.textContent=msg;t.className='toast show '+type;setTimeout(()=>t.className='toast',2600)}
function seed(){
 if(!localStorage.getItem(LS.admins)) set(LS.admins,[{id:'admin_1',nombre:'Administrador',apellidos:'Flores Mobiliario',correo:'admin@flores.com',telefono:'4180000000',password:'admin123',rol:'Administrador principal'}]);
 if(!localStorage.getItem(LS.users)) set(LS.users,[]);
 if(!localStorage.getItem(LS.quotes)) set(LS.quotes,[]);
 if(!localStorage.getItem(LS.products)) set(LS.products,[
  {id:'p1',nombre:'Silla Ejecutiva Ergónomica',categoria:'Sillas',color:'Negro',medida:'60 x 58 x 110 cm',stock:18,precio:2450,img:'silla.jpg',descripcion:'Silla profesional con soporte lumbar, ajuste de altura y acabado resistente para oficina.'},
  {id:'p2',nombre:'Escritorio Ejecutivo Roble',categoria:'Escritorios',color:'Roble natural',medida:'160 x 75 x 75 cm',stock:10,precio:6890,img:'escritorio.jpg',descripcion:'Escritorio amplio con diseño moderno, cubierta resistente y presencia ejecutiva.'},
  {id:'p3',nombre:'Librero Modular Oficina',categoria:'Almacenamiento',color:'Nogal',medida:'90 x 35 x 180 cm',stock:12,precio:3990,img:'librero.jpeg',descripcion:'Librero de gran capacidad para documentos, decoración y organización profesional.'},
  {id:'p4',nombre:'Mesa de Juntas Premium',categoria:'Mesas',color:'Caoba',medida:'240 x 110 x 75 cm',stock:6,precio:11900,img:'mesa.jpeg',descripcion:'Mesa de juntas robusta para salas directivas y espacios colaborativos.'},
  {id:'p5',nombre:'Mostrador de Recepción',categoria:'Recepción',color:'Blanco/Nogal',medida:'180 x 60 x 110 cm',stock:4,precio:14990,img:'recepcion.jpeg',descripcion:'Recepción moderna para oficinas, consultorios y puntos de atención al cliente.'},
  {id:'p6',nombre:'Archivero Metálico 4 Gavetas',categoria:'Almacenamiento',color:'Gris',medida:'46 x 62 x 132 cm',stock:15,precio:3290,img:'archivero.jpg',descripcion:'Archivero seguro y funcional para expedientes, contratos y documentos de uso diario.'}
 ]);
}
function session(){return get(LS.session,null)} function current(){let s=session(); if(!s)return null; return get(s.role==='admin'?LS.admins:LS.users).find(x=>x.id===s.id)||null}
function logout(){localStorage.removeItem(LS.session); location.href='index.html'}
function nav(){seed();let s=session(),u=current();qsa('[data-user-name]').forEach(e=>e.textContent=u?u.nombre:'Invitado');qsa('[data-auth]').forEach(e=>e.style.display=s?'inline-flex':'none');qsa('[data-guest]').forEach(e=>e.style.display=s?'none':'inline-flex');qsa('[data-admin]').forEach(e=>e.style.display=s?.role==='admin'?'inline-flex':'none');qsa('[data-user]').forEach(e=>e.style.display=s?.role==='user'?'inline-flex':'none');let b=qs('#mobileMenu'); if(b)b.onclick=()=>qs('.nav').classList.toggle('open')}
function requireRole(role){let s=session(); if(!s || (role&&s.role!==role)){location.href='login.html';return false}return true}
function registerUser(ev){ev.preventDefault();let f=ev.target,users=get(LS.users);let data=Object.fromEntries(new FormData(f).entries());if(users.some(u=>u.correo.toLowerCase()===data.correo.toLowerCase()))return toast('Ese correo ya está registrado','danger');let u={id:uid('user'),nombre:data.nombre.trim(),apellidos:data.apellidos.trim(),correo:data.correo.trim(),telefono:data.telefono.trim(),password:data.password,creado:new Date().toISOString()};users.push(u);set(LS.users,users);set(LS.session,{role:'user',id:u.id});toast('Cuenta creada correctamente','ok');setTimeout(()=>location.href='productos.html',700)}
function login(ev){ev.preventDefault();let d=Object.fromEntries(new FormData(ev.target).entries());let admins=get(LS.admins),users=get(LS.users);let a=admins.find(x=>x.correo.toLowerCase()===d.correo.toLowerCase()&&x.password===d.password);if(a){set(LS.session,{role:'admin',id:a.id});location.href='admin.html';return}let u=users.find(x=>x.correo.toLowerCase()===d.correo.toLowerCase()&&x.password===d.password);if(u){set(LS.session,{role:'user',id:u.id});location.href='productos.html';return}toast('Correo o contraseña incorrectos','danger')}
function productCard(p){return `<article class="card product"><img class="product-img" src="${p.img}" alt="${p.nombre}"><div class="product-body"><span class="pill">${p.categoria} · Stock ${p.stock}</span><h3>${p.nombre}</h3><p>${p.descripcion}</p><div class="mini">Color: ${p.color} · Medida: ${p.medida}</div><div class="product-meta"><strong class="price">${money(p.precio)}</strong><button class="btn btn-primary" onclick="addToQuote('${p.id}')">Agregar</button></div></div></article>`}
function renderProducts(){let box=qs('#productosGrid'); if(!box)return; let products=get(LS.products);let cats=['Todas',...new Set(products.map(p=>p.categoria))];let sel=qs('#categoria'); if(sel&&!sel.dataset.ready){sel.innerHTML=cats.map(c=>`<option>${c}</option>`).join(''); sel.dataset.ready=1; ['input','change'].forEach(e=>qsa('#buscar,#categoria,#orden').forEach(x=>x.addEventListener(e,renderProducts)))}let term=(qs('#buscar')?.value||'').toLowerCase(),cat=qs('#categoria')?.value||'Todas',orden=qs('#orden')?.value||'';let list=products.filter(p=>(cat==='Todas'||p.categoria===cat)&&(`${p.nombre} ${p.categoria} ${p.color}`.toLowerCase().includes(term))); if(orden==='menor')list.sort((a,b)=>a.precio-b.precio); if(orden==='mayor')list.sort((a,b)=>b.precio-a.precio); box.innerHTML=list.length?list.map(productCard).join(''):'<div class="empty card">No encontramos productos con esos filtros.</div>'}
function activeQuote(){let s=session(); if(!s||s.role!=='user')return null;let id=localStorage.getItem(LS.activeQuote);let quotes=get(LS.quotes);let q=quotes.find(x=>x.id===id&&x.userId===s.id&&x.estado==='borrador');if(!q){q={id:uid('cot'),userId:s.id,items:[],estado:'borrador',fecha:new Date().toISOString(),notas:''};quotes.push(q);set(LS.quotes,quotes);localStorage.setItem(LS.activeQuote,q.id)}return q}
function saveQuote(q){let arr=get(LS.quotes);let i=arr.findIndex(x=>x.id===q.id); if(i>=0)arr[i]=q; else arr.push(q);set(LS.quotes,arr)}
function addToQuote(pid){if(!requireRole('user'))return;let p=get(LS.products).find(x=>x.id===pid); if(!p||p.stock<1)return toast('Producto sin stock','danger');let q=activeQuote();let it=q.items.find(x=>x.productId===pid); if(it)it.cantidad++; else q.items.push({productId:pid,cantidad:1,precio:p.precio});q.fecha=new Date().toISOString();saveQuote(q);toast('Producto agregado a tu cotización','ok')}
function calc(q){let products=get(LS.products);let items=(q.items||[]).map(i=>{let p=products.find(x=>x.id===i.productId)||{};let precio=Number(i.precio??p.precio??0);let cantidad=Number(i.cantidad||1);return {...i,producto:p,precio,cantidad,subtotal:precio*cantidad}});let total=items.reduce((a,b)=>a+b.subtotal,0);let cantidad=items.reduce((a,b)=>a+b.cantidad,0);return{items,total,cantidad}}
function renderQuote(){if(!qs('#quoteBody'))return;if(!requireRole('user'))return;let q=activeQuote(),c=calc(q);let tbody=qs('#quoteBody');tbody.innerHTML=c.items.length?c.items.map(i=>`<tr><td><b>${i.producto.nombre||'Producto eliminado'}</b><div class="mini">${i.producto.categoria||''} · ${i.producto.medida||''}</div></td><td>${money(i.precio)}</td><td><div class="qty"><button class="btn btn-small" onclick="changeQty('${i.productId}',-1)">−</button><input class="input" type="number" min="1" value="${i.cantidad}" onchange="setQty('${i.productId}',this.value)"><button class="btn btn-small" onclick="changeQty('${i.productId}',1)">+</button></div></td><td><b>${money(i.subtotal)}</b></td><td><button class="btn btn-danger btn-small" onclick="removeItem('${i.productId}')">Eliminar</button></td></tr>`).join(''):`<tr><td colspan="5"><div class="empty">Tu cotización está vacía. Agrega productos desde el catálogo.</div></td></tr>`;qs('#quoteTotal').textContent=money(c.total);qs('#quoteCantidad').textContent=c.cantidad;qs('#quoteProductos').textContent=c.items.length;qs('#submitQuote').disabled=!c.items.length;qs('#quoteNotas').value=q.notas||'';renderUserQuotes()}
function changeQty(pid,d){let q=activeQuote(),it=q.items.find(x=>x.productId===pid); if(!it)return;it.cantidad=Math.max(1,Number(it.cantidad)+d);saveQuote(q);renderQuote()}function setQty(pid,v){let q=activeQuote(),it=q.items.find(x=>x.productId===pid); if(!it)return;it.cantidad=Math.max(1,Number(v)||1);saveQuote(q);renderQuote()}function removeItem(pid){let q=activeQuote();q.items=q.items.filter(i=>i.productId!==pid);saveQuote(q);renderQuote();toast('Producto eliminado')}
function submitQuote(){let q=activeQuote();q.notas=qs('#quoteNotas').value.trim();q.estado='enviada';q.enviada=new Date().toISOString();saveQuote(q);localStorage.removeItem(LS.activeQuote);toast('Cotización enviada al administrador','ok');setTimeout(()=>renderQuote(),600)}
function renderUserQuotes(){let box=qs('#misCotizaciones'); if(!box)return;let s=session();let list=get(LS.quotes).filter(q=>q.userId===s.id&&q.estado!=='borrador').sort((a,b)=>b.fecha.localeCompare(a.fecha));box.innerHTML=list.length?list.map(q=>{let c=calc(q);return `<div class="card card-pad quote-card"><div><span class="badge ${q.estado}">${q.estado}</span><h3>Cotización ${q.id.slice(-6).toUpperCase()}</h3><div class="mini">${new Date(q.fecha).toLocaleString('es-MX')} · ${c.cantidad} piezas · ${money(c.total)}</div><div class="quote-items">${c.items.map(i=>`<span>${i.cantidad}× ${i.producto.nombre||'Producto'}</span>`).join('')}</div>${q.notas?`<p class="mini"><b>Notas:</b> ${q.notas}</p>`:''}</div><div><button class="btn btn-danger btn-small" onclick="deleteQuote('${q.id}')">Eliminar</button></div></div>`}).join(''):'<div class="empty card">Aún no tienes cotizaciones enviadas.</div>'}
function deleteQuote(id){set(LS.quotes,get(LS.quotes).filter(q=>q.id!==id));toast('Cotización eliminada');renderQuote();renderAdminQuotes?.()}
function renderProfile(){if(!qs('#perfilForm'))return;if(!requireRole('user'))return;let u=current();['nombre','apellidos','correo','telefono','password'].forEach(k=>qs(`[name=${k}]`).value=u[k]||'');renderUserQuotes()}function saveProfile(ev){ev.preventDefault();let d=Object.fromEntries(new FormData(ev.target).entries()),users=get(LS.users),u=current();Object.assign(u,d);set(LS.users,users.map(x=>x.id===u.id?u:x));toast('Datos actualizados','ok');nav()}function deleteAccount(){if(!confirm('¿Eliminar tu cuenta y tus cotizaciones?'))return;let s=session();set(LS.users,get(LS.users).filter(u=>u.id!==s.id));set(LS.quotes,get(LS.quotes).filter(q=>q.userId!==s.id));localStorage.removeItem(LS.session);localStorage.removeItem(LS.activeQuote);location.href='index.html'}
function adminTab(id){qsa('[data-panel]').forEach(p=>p.style.display=p.dataset.panel===id?'block':'none');qsa('.side a').forEach(a=>a.classList.toggle('active',a.dataset.go===id)); if(id==='productos')renderAdminProducts(); if(id==='cotizaciones')renderAdminQuotes(); if(id==='adminDatos')renderAdminProfile();}
function renderAdminProducts(){let box=qs('#adminProducts'); if(!box)return;let list=get(LS.products);box.innerHTML=list.map(p=>`<tr><td><img src="${p.img}" style="width:70px;height:54px;object-fit:cover;border-radius:10px"></td><td><b>${p.nombre}</b><div class="mini">${p.categoria}</div></td><td>${money(p.precio)}</td><td>${p.stock}</td><td><button class="btn btn-small" onclick='loadProduct(${JSON.stringify(p)})'>Editar</button> <button class="btn btn-danger btn-small" onclick="deleteProduct('${p.id}')">Eliminar</button></td></tr>`).join('')}
function loadProduct(p){let f=qs('#productForm');Object.keys(p).forEach(k=>{if(f[k])f[k].value=p[k]});window.scrollTo({top:f.offsetTop-100,behavior:'smooth'})}function clearProduct(){qs('#productForm').reset();qs('#productForm').id.value=''}function saveProduct(ev){ev.preventDefault();let d=Object.fromEntries(new FormData(ev.target).entries());d.precio=Number(d.precio);d.stock=Number(d.stock);let arr=get(LS.products);if(d.id){arr=arr.map(p=>p.id===d.id?d:p);toast('Producto actualizado','ok')}else{d.id=uid('p');arr.push(d);toast('Producto agregado','ok')}set(LS.products,arr);clearProduct();renderAdminProducts()}function deleteProduct(id){if(!confirm('¿Eliminar producto?'))return;set(LS.products,get(LS.products).filter(p=>p.id!==id));renderAdminProducts();toast('Producto eliminado')}
function renderAdminQuotes(){let box=qs('#adminQuotes'); if(!box)return;let users=get(LS.users),list=get(LS.quotes).filter(q=>q.estado!=='borrador').sort((a,b)=>(b.enviada||b.fecha).localeCompare(a.enviada||a.fecha));box.innerHTML=list.length?list.map(q=>{let u=users.find(x=>x.id===q.userId)||{},c=calc(q);return `<div class="card card-pad"><div class="quote-card"><div><span class="badge ${q.estado}">${q.estado}</span><h3>${u.nombre||'Usuario'} ${u.apellidos||''}</h3><div class="mini">${u.correo||''} · ${u.telefono||''} · ${money(c.total)}</div><div class="quote-items">${c.items.map(i=>`<span><b>${i.productId}</b> · ${i.cantidad}× ${i.producto.nombre||'Producto'} (${money(i.subtotal)})</span>`).join('')}</div><textarea class="input" rows="2" id="notes_${q.id}" placeholder="Notas o cambios solicitados">${q.notas||''}</textarea></div><div style="display:flex;gap:8px;flex-wrap:wrap;justify-content:end"><button class="btn btn-success btn-small" onclick="setQuoteStatus('${q.id}','aceptada')">Aceptar</button><button class="btn btn-small" onclick="editAdminQuote('${q.id}')">Editar</button><button class="btn btn-danger btn-small" onclick="deleteQuote('${q.id}')">Eliminar</button></div></div></div>`}).join(''):'<div class="empty card">No hay cotizaciones enviadas.</div>'}
function setQuoteStatus(id,estado){let arr=get(LS.quotes);let q=arr.find(x=>x.id===id);if(!q)return;if(estado==='aceptada'&&q.estado!=='aceptada'){let products=get(LS.products);for(let it of q.items||[]){let p=products.find(x=>x.id===it.productId);if(p)p.stock=Math.max(0,Number(p.stock||0)-Number(it.cantidad||0));}set(LS.products,products)}q.estado=estado;q.notas=qs('#notes_'+id)?.value||q.notas;q.respuesta='Cotización revisada por administración';q.actualizada=new Date().toISOString();set(LS.quotes,arr);renderAdminQuotes();toast('Cotización actualizada','ok')}function editAdminQuote(id){let arr=get(LS.quotes),q=arr.find(x=>x.id===id),c=calc(q);let detalle=c.items.map(i=>`${i.producto.nombre||i.productId}: cantidad actual ${i.cantidad}`).join('\n');let r=prompt('Edita cantidades con formato: IDProducto=cantidad\nProductos:\n'+detalle+'\n\nEjemplo: p1=2,p3=1','');if(r){r.split(',').forEach(pair=>{let [pid,qty]=pair.split('=').map(x=>x.trim());let it=q.items.find(i=>i.productId===pid);if(it)it.cantidad=Math.max(1,Number(qty)||it.cantidad)});q.notas=qs('#notes_'+id)?.value||q.notas;set(LS.quotes,arr);renderAdminQuotes();toast('Cambios aplicados','ok')}}

function registerAdmin(ev){ev.preventDefault();let f=ev.target,d=Object.fromEntries(new FormData(f).entries());if((d.clave||'').trim()!=='DUENA-FLORES')return toast('Clave de autorización incorrecta','danger');let admins=get(LS.admins);if(admins.some(a=>a.correo.toLowerCase()===d.correo.toLowerCase()))return toast('Ese correo administrativo ya existe','danger');let a={id:uid('admin'),nombre:d.nombre.trim(),apellidos:d.apellidos.trim(),correo:d.correo.trim(),telefono:d.telefono.trim(),password:d.password,rol:d.rol||'Administrador',creado:new Date().toISOString()};admins.push(a);set(LS.admins,admins);set(LS.session,{role:'admin',id:a.id});toast('Administrador registrado correctamente','ok');setTimeout(()=>location.href='admin.html',700)}
function deleteAdminAccount(){let s=session();if(!s||s.role!=='admin')return;let admins=get(LS.admins);if(admins.length<=1)return toast('Debe existir al menos un administrador','danger');let key=prompt('Para eliminar esta cuenta, escribe la clave de la dueña:');if(key!=='DUENA-FLORES')return toast('Confirmación incorrecta','danger');if(!confirm('¿Eliminar definitivamente esta cuenta de administrador?'))return;set(LS.admins,admins.filter(a=>a.id!==s.id));localStorage.removeItem(LS.session);location.href='index.html'}
function exportBackup(){let data={fecha:new Date().toISOString(),version:'RF1-RF19',users:get(LS.users),admins:get(LS.admins),products:get(LS.products),quotes:get(LS.quotes)};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='respaldo_flores_mobiliario.json';a.click();URL.revokeObjectURL(a.href);toast('Respaldo generado','ok')}
function importBackup(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!confirm('¿Importar respaldo y reemplazar datos locales?'))return;if(d.users)set(LS.users,d.users);if(d.admins)set(LS.admins,d.admins);if(d.products)set(LS.products,d.products);if(d.quotes)set(LS.quotes,d.quotes);toast('Respaldo importado','ok');setTimeout(()=>location.reload(),700)}catch(e){toast('Archivo de respaldo inválido','danger')}};r.readAsText(file)}

function renderAdminProfile(){let f=qs('#adminForm'); if(!f)return;let a=current();['nombre','apellidos','correo','telefono','password','rol'].forEach(k=>{if(f[k])f[k].value=a[k]||''})}function saveAdminProfile(ev){ev.preventDefault();let d=Object.fromEntries(new FormData(ev.target).entries()),admins=get(LS.admins),a=current();Object.assign(a,d);set(LS.admins,admins.map(x=>x.id===a.id?a:x));toast('Datos del administrador guardados','ok');nav()}function reportes(){if(!qs('#repVentas'))return;if(!requireRole('admin'))return;let qsx=get(LS.quotes),prods=get(LS.products);let accepted=qsx.filter(q=>q.estado==='aceptada');let total=accepted.reduce((a,q)=>a+calc(q).total,0);qs('#repVentas').textContent=money(total);qs('#repCot').textContent=qsx.filter(q=>q.estado!=='borrador').length;qs('#repProd').textContent=prods.length;qs('#repStock').textContent=prods.reduce((a,p)=>a+Number(p.stock),0)}
document.addEventListener('DOMContentLoaded',()=>{nav();renderProducts();renderQuote();renderProfile();reportes();if(qs('#registerForm'))qs('#registerForm').onsubmit=registerUser;if(qs('#adminRegisterForm'))qs('#adminRegisterForm').onsubmit=registerAdmin;if(qs('#loginForm'))qs('#loginForm').onsubmit=login;if(qs('#perfilForm'))qs('#perfilForm').onsubmit=saveProfile;if(qs('#submitQuote'))qs('#submitQuote').onclick=submitQuote;if(qs('#deleteAccount'))qs('#deleteAccount').onclick=deleteAccount;if(qs('#deleteAdmin'))qs('#deleteAdmin').onclick=deleteAdminAccount;if(qs('#productForm'))qs('#productForm').onsubmit=saveProduct;if(qs('#adminForm'))qs('#adminForm').onsubmit=saveAdminProfile;if(qs('#adminPage')&&requireRole('admin'))adminTab('productos')});
